### ISSUE TITLE
Umbrella issue about prompt

### ISSUE THREAD

**Issue by apstndb** [apstndb/spanner-mycli#13]
* [x] Customizable prompt2 #35 
  * [x] lexer status in prompt2
* [x] allow newlines in prompt #15 
* [x] Use `%` instead of `\` #15 
  * Because `\` is treated as a special character in many context, especially `go-flags` needs to escape `\`.
* [x] Showing system variables in prompt

Related issue in original spanner-cli

* https://github.com/cloudspannerecosystem/spanner-cli/issues/183
* https://github.com/cloudspannerecosystem/spanner-cli/issues/186
* https://github.com/cloudspannerecosystem/spanner-cli/issues/187
* https://github.com/cloudspannerecosystem/spanner-cli/issues/188

**Comment by apstndb** [comment]
Close this issue because I have finished planned features.
